name: Get citations from Overton

on:
  workflow_dispatch:
  schedule:
    - cron: "0 12 * * 0"  # Run every Sunday at 6am (UTC)

permissions:
  contents: write
    
jobs:
  run-notebook:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v3

      - name: Install dependencies
        run: pip install papermill ipython ipykernel pandas==2.3.3 requests numpy
        
      - name: Run Jupyter Notebook
        run: |

          papermill nerc_dataset_citations_overton.ipynb executed_notebooks/nerc_dataset_citations_overton_executed.ipynb # nerc_dataset_citations_part1_executed.ipynb # keep "_executed.ipynb" to see errors


      - name: Commit and push results
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add "Results/intermediate_data/latest_results_overton.csv" "Results/intermediate_data/latest_results_overton.pkl" "nerc_dataset_citations_overton.ipynb" "executed_notebooks/nerc_dataset_citations_overton_executed.ipynb"
          git commit -m "Regular action, updates latest_results_overton.csv"
          git push https://github.com/NERC-EDS/citationNotebook.git main

        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
